export const MAX_SCORE = 121

export const POSITION_LABELS = {
  top: 'TOP',
  jungle: 'JUNGLE',
  mid: 'MID',
  adc: 'ADC',
  support: 'SUPPORT',
}

export const POSITION_ORDER = ['top', 'jungle', 'mid', 'adc', 'support']


export const players = [
  { id: 'p01', active: true, name: '윤지현', nickname: '그대의 안식처', tag: 'kr1', positions: { top: 26 } },
  { id: 'p02', active: true, name: '이진영', nickname: '조흔뎅괜찮은뎅', tag: 'kr1', positions: { top: 25, support: 27 } },
  { id: 'p03', active: true, name: '한만서', nickname: '앞날이 없는 인간', tag: '노사람', positions: { top: 21, adc: 24 } },
  { id: 'p04', active: true, name: '하지훈', nickname: '맹독의 호흡', tag: 'kor1', positions: { top: 20 } },
  { id: 'p05', active: true, name: '박규영', nickname: '핀란드해변대게', tag: '7777', positions: { top: 19, mid: 24, adc: 23 } },
  { id: 'p06', active: true, name: '김정섭', nickname: '조심성 없는 인간', tag: '노사람', positions: { top: 19, mid: 23 } },
  { id: 'p07', active: true, name: '박세준', nickname: '오른손에 돈까스 망치', tag: 'kr91', positions: { top: 19 } },
  { id: 'p08', active: true, name: '김성현', nickname: '에이드좋아', tag: 'kr1', positions: { top: 18, mid: 24 } },
  { id: 'p09', active: true, name: '안수빈', nickname: '종료함', tag: 'kr1', positions: { top: 18, adc: 21 } },
  { id: 'p10', active: true, name: '이근호', nickname: '근 들', tag: '진들', positions: { top: 18, adc: 23 } },
  { id: 'p11', active: true, name: '이은효', nickname: '이으뇨', tag: 'kr0', positions: { top: 18 } },
  { id: 'p12', active: true, name: '남주찬', nickname: '1티어오함마', tag: 'kr1', positions: { top: 17, support: 18 } },
  { id: 'p13', active: true, name: '임경태', nickname: '박봉자', tag: 'kr2', positions: { top: 16, jungle: 24 } },
  { id: 'p14', active: true, name: '이재원', nickname: '초코과자사각사각', tag: '', positions: { top: 12, mid: 12 } },
  { id: 'p15', active: true, name: '이새하', nickname: '', tag: '', positions: { top: 7 } },
  { id: 'p16', active: true, name: '윤희조', nickname: '흉폭한폼폼이', tag: '6547', positions: { top: 4 } },
  { id: 'p17', active: true, name: '백송이', nickname: '렉사이', tag: '7328', positions: { jungle: 36, support: 27 } },
  { id: 'p18', active: true, name: '백건휘', nickname: 'NyanBlanc', tag: 'kr1', positions: { jungle: 34, adc: 27 } },
  { id: 'p19', active: true, name: '양승일', nickname: '승 일', tag: 'kr1', positions: { jungle: 32, adc: 32 } },
  { id: 'p20', active: true, name: '박성진(97)', nickname: '아침의모닝빵', tag: 'kr1', positions: { jungle: 31, mid: 29 } },
  { id: 'p21', active: true, name: '황기성', nickname: '황기성', tag: 'kr1', positions: { jungle: 31, support: 27 } },
  { id: 'p22', active: true, name: '김재훈', nickname: 'J H', tag: 'LOL', positions: { jungle: 29 } },
  { id: 'p23', active: true, name: '송재정', nickname: '귀찮다', tag: 'kr2', positions: { jungle: 28 } },
  { id: 'p24', active: true, name: '박성진(98)', nickname: '냥냥이가왈왈', tag: 'kr1', positions: { jungle: 27 } },
  { id: 'p25', active: true, name: '조용범', nickname: '마스야드', tag: 'kr1', positions: { jungle: 27, support: 19 } },
  { id: 'p26', active: true, name: '문우준', nickname: '고혈충', tag: 'kr1', positions: { jungle: 26 } },
  { id: 'p27', active: true, name: '민정호', nickname: '사랑이 우스운 나이', tag: '사우', positions: { jungle: 25, mid: 23 } },
  { id: 'p28', active: true, name: '이석현', nickname: '', tag: '', positions: { jungle: 20 } },
  { id: 'p29', active: true, name: '방재현', nickname: '고랭지농업종사자', tag: 'kr308', positions: { jungle: 18, support: 17 } },
  { id: 'p30', active: true, name: '김건', nickname: 'jagosipeum', tag: '777', positions: { mid: 34 } },
  { id: 'p31', active: true, name: '상훈', nickname: 'nochatnoping', tag: 'plz', positions: { mid: 34 } },
  { id: 'p32', active: true, name: '이천우', nickname: '천 우', tag: '경주이', positions: { mid: 31 } },
  { id: 'p33', active: true, name: '김보겸', nickname: '팔보채마시써', tag: 'kr1', positions: { mid: 30 } },
  { id: 'p34', active: true, name: '박혜성', nickname: '혜 성', tag: '713', positions: { mid: 30, adc: 32 } },
  { id: 'p35', active: true, name: '안수환', nickname: '정점이 될 사나이', tag: '1213', positions: { mid: 30, adc: 32 } },
  { id: 'p36', active: true, name: '윤태영', nickname: '윤태랜드', tag: 'kr1', positions: { mid: 29, adc: 32 } },
  { id: 'p37', active: true, name: '남주영', nickname: '꼬맹이', tag: '1127', positions: { mid: 28 } },
  { id: 'p38', active: true, name: '강세훈', nickname: '강세훈', tag: '강세훈', positions: { mid: 26, support: 26 } },
  { id: 'p39', active: true, name: '강희구', nickname: 'sunnyside of', tag: 'kr0', positions: { mid: 26 } },
  { id: 'p40', active: true, name: '조유성', nickname: '작은노옴', tag: 'kr1', positions: { mid: 25 } },
  { id: 'p41', active: true, name: '권태희', nickname: '꼰태히', tag: 'kr1', positions: { mid: 24, adc: 22 } },
  { id: 'p42', active: true, name: '최진실', nickname: '스치는봄바람', tag: 'kr1', positions: { mid: 23, support: 19 } },
  { id: 'p43', active: true, name: '민승환', nickname: 'Pianeta', tag: 'kr1', positions: { mid: 21, support: 21 } },
  { id: 'p44', active: true, name: '윤수정', nickname: '꾸꾸', tag: 'kr92', positions: { mid: 17, support: 15 } },
  { id: 'p45', active: true, name: '윤정환', nickname: '아무코토모탯쥬', tag: 'kr1', positions: { mid: 16 } },
  { id: 'p46', active: true, name: '김덕송', nickname: '', tag: '', positions: { mid: 11 } },
  { id: 'p47', active: true, name: '김지훈(구로)', nickname: '씹덕육수', tag: 'kr1', positions: { adc: 26 } },
  { id: 'p48', active: true, name: '정민형', nickname: '샤를리스', tag: 'kr1', positions: { adc: 26 } },
  { id: 'p49', active: true, name: '손희승', nickname: '인내심 없는 인간', tag: '노사람', positions: { adc: 24, support: 21 } },
  { id: 'p50', active: true, name: '조서영', nickname: '뿌 직', tag: 'sexy', positions: { adc: 24, support: 22 } },
  { id: 'p51', active: true, name: '권민경', nickname: '윤막례', tag: 'kr2', positions: { adc: 19, support: 22 } },
  { id: 'p52', active: true, name: '김영재', nickname: 'Jeroaeswi', tag: 'Steam', positions: { adc: 12 } },
  { id: 'p53', active: true, name: '김채연', nickname: '치매할매', tag: 'k1r', positions: { support: 22 } },
  { id: 'p54', active: true, name: '이다요', nickname: '피곤하다요', tag: 'kr1', positions: { support: 20 } },
  { id: 'p55', active: true, name: '이경섭', nickname: '아이그럼요', tag: 'kr1', positions: { support: 17 } },
  { id: 'p56', active: true, name: '한승훈', nickname: '한떠꾸', tag: '5622', positions: { support: 17 } },
  { id: 'p57', active: true, name: '오경희', nickname: '파리두마시라넷', tag: '8868', positions: { support: 15 } },
  { id: 'p58', active: true, name: '이여진', nickname: '귀여운단이', tag: 'kr1', positions: { support: 15 } },
  { id: 'p59', active: true, name: '이훈기', nickname: '이후닉', tag: 'kr1', positions: { support: 15 } },
  { id: 'p60', active: true, name: '신지현', nickname: '', tag: '', positions: { support: 14 } },
  { id: 'p61', active: true, name: '김미형', nickname: '콤과체리', tag: '9284', positions: { support: 13 } },
  { id: 'p62', active: true, name: '이승봉', nickname: 'Hiseeker', tag: 'kr1', positions: { support: 11 } },
  { id: 'p63', active: false, name: '김재민', nickname: 'closetome', tag: '7045', positions: { jungle: 29 } },
]

export const teams = [
  { id: 'team01', name: '총이요', alive: false, players: { top: 'p03', jungle: 'p18', mid: 'p45', adc: 'p49', support: 'p50' } },
  { id: 'team02', name: '가성비', alive: false, players: { top: 'p06', jungle: 'p20', mid: 'p40', adc: 'p47', support: 'p58' } },
  { id: 'team03', name: '진실1', alive: false, players: { top: 'p11', jungle: 'p24', mid: 'p42', adc: 'p34', support: 'p56' } },
  { id: 'team04', name: '수빈경태보겸막례기성', alive: false, players: { top: 'p09', jungle: 'p13', mid: 'p33', adc: 'p51', support: 'p21' } },
  { id: 'team05', name: '천우살려', alive: false, players: { top: 'p12', jungle: 'p27', mid: 'p32', adc: 'p10', support: 'p43' } },
  { id: 'team06', name: '오합지존', alive: false, players: { top: 'p07', jungle: 'p17', mid: 'p37', adc: 'p10', support: 'p44' } },
  { id: 'team07', name: '진실2', alive: false, players: { top: 'p11', jungle: 'p24', mid: 'p42', adc: 'p34', support: 'p56' } },
  { id: 'team08', name: '치매', alive: true, players: { top: 'p12', jungle: 'p26', mid: 'p08', adc: 'p36', support: 'p53' } },
  { id: 'team09', name: '우리탑해줘~', alive: false, players: { top: 'p01', jungle: 'p63', mid: 'p41', adc: 'p10', support: 'p59' } },
  { id: 'team10', name: '이멤버리멤버', alive: false, players: { top: 'p07', jungle: 'p13', mid: 'p32', adc: 'p34', support: 'p44' } },
  { id: 'team11', name: '진실3', alive: true, players: { top: 'p11', jungle: 'p24', mid: 'p42', adc: 'p34', support: 'p56' } },
  { id: 'team12', name: '세준', alive: false, players: { top: 'p07', jungle: 'p17', mid: 'p41', adc: 'p48', support: 'p44' } },
  { id: 'team13', name: '만재천막희', alive: true, players: { top: 'p03', jungle: 'p22', mid: 'p32', adc: 'p51', support: 'p49' } },
  { id: 'team14', name: '부술게?', alive: false, players: { top: 'p07', jungle: 'p27', mid: 'p41', adc: 'p18', support: 'p38' } },
  { id: 'team15', name: '근호', alive: true, players: { top: 'p07', jungle: 'p20', mid: 'p39', adc: 'p10', support: 'p43' } },
  { id: 'team16', name: '기성', alive: false, players: { top: 'p04', jungle: 'p21', mid: 'p45', adc: 'p18', support: 'p17' } },
  { id: 'team17', name: '업투유~', alive: true, players: { top: 'p07', jungle: 'p20', mid: 'p44', adc: 'p18', support: 'p21' } },
]

export const matches = [
  { id: 'm01', date: '2026-09-02', teamA: 'team02', teamB: 'team03', scoreA: 2, scoreB: 1 },
  { id: 'm02', date: '2026-09-06', teamA: 'team01', teamB: 'team05', scoreA: 2, scoreB: 0 },
  { id: 'm03', date: '2026-09-09', teamA: 'team06', teamB: 'team07', scoreA: 2, scoreB: 1 },
  { id: 'm04', date: '2026-09-10', teamA: 'team01', teamB: 'team06', scoreA: 2, scoreB: 1 },
  { id: 'm05', date: '2026-09-11', teamA: 'team09', teamB: 'team04', scoreA: 2, scoreB: 1 },
  { id: 'm06', date: '2026-09-14', teamA: 'team02', teamB: 'team09', scoreA: 2, scoreB: 0 },
  { id: 'm07', date: '2026-09-14', teamA: 'team08', teamB: 'team10', scoreA: 2, scoreB: 0 },
  { id: 'm08', date: '2026-09-15', teamA: 'team11', teamB: 'team12', scoreA: 2, scoreB: 1 },
  { id: 'm09', date: '2026-09-15', teamA: 'team02', teamB: 'team01', scoreA: 2, scoreB: 1 },
  { id: 'm10', date: '2026-09-18', teamA: 'team14', teamB: 'team02', scoreA: 2, scoreB: 0 },
  { id: 'm11', date: '2026-09-18', teamA: 'team13', teamB: 'team14', scoreA: 2, scoreB: 1 },
  { id: 'm12', date: '2026-09-20', teamA: 'team15', teamB: 'team16', scoreA: 2, scoreB: 0 },
]